spring.application.name=apigateway
server.port=${SERVER_PORT:8083}
spring.http.clients.imperative.factory=simple

gateway.services.inventory-base-url=${GATEWAY_INVENTORY_URL:http://localhost:8080}
gateway.services.booking-base-url=${GATEWAY_BOOKING_URL:http://localhost:8081}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8091/realms/book-my-event}
spring.security.oauth2.resourceserver.jwt.audiences=${KEYCLOAK_AUDIENCE:book-my-event-api}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Inventory API
springdoc.swagger-ui.urls[0].url=/docs/inventory/v3/api-docs/public
springdoc.swagger-ui.urls[1].name=Booking API
springdoc.swagger-ui.urls[1].url=/docs/booking/v3/api-docs/public
springdoc.swagger-ui.urls-primary-name=Inventory API
springdoc.swagger-ui.disable-swagger-default-url=true
