spring.application.name=apigateway
server.port=${SERVER_PORT:8083}
spring.http.clients.imperative.factory=simple

gateway.services.inventory-base-url=${GATEWAY_INVENTORY_URL:http://localhost:8080}
gateway.services.booking-base-url=${GATEWAY_BOOKING_URL:http://localhost:8081}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Inventory API
springdoc.swagger-ui.urls[0].url=/docs/inventory/v3/api-docs/public
springdoc.swagger-ui.urls[1].name=Booking API
springdoc.swagger-ui.urls[1].url=/docs/booking/v3/api-docs/public
springdoc.swagger-ui.urls-primary-name=Inventory API
springdoc.swagger-ui.disable-swagger-default-url=true
