#!/bin/sh
set -eu

# This job runs after MySQL is healthy and is safe to run on every Compose start.
# Application tables are intentionally excluded; each service creates only its
# own tables through its Flyway migrations.
export MYSQL_PWD="${MYSQL_ROOT_PASSWORD}"

mysql --protocol=TCP --host=mysql --user=root <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${INVENTORY_DB_NAME}\`
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS \`${BOOKING_DB_NAME}\`
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS \`${ORDER_DB_NAME}\`
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${INVENTORY_DB_USERNAME}'@'%' IDENTIFIED BY '${INVENTORY_DB_PASSWORD}';
ALTER USER '${INVENTORY_DB_USERNAME}'@'%' IDENTIFIED BY '${INVENTORY_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${INVENTORY_DB_NAME}\`.* TO '${INVENTORY_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${BOOKING_DB_USERNAME}'@'%' IDENTIFIED BY '${BOOKING_DB_PASSWORD}';
ALTER USER '${BOOKING_DB_USERNAME}'@'%' IDENTIFIED BY '${BOOKING_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${BOOKING_DB_NAME}\`.* TO '${BOOKING_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${ORDER_DB_USERNAME}'@'%' IDENTIFIED BY '${ORDER_DB_PASSWORD}';
ALTER USER '${ORDER_DB_USERNAME}'@'%' IDENTIFIED BY '${ORDER_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${ORDER_DB_NAME}\`.* TO '${ORDER_DB_USERNAME}'@'%';

FLUSH PRIVILEGES;
EOSQL
